name: VoiceChatPlugin
main: com.example.voicechatplugin.Main
version: 1.0
author: Naufal90
api-version: 1.20
depend: [voicechat]

commands:
  voicechat:
    description: Mengelola grup voice chat
    usage: /voicechat [create|join|leave] [nama_grup]
    permission: voicechatplugin.use

permissions:
  voicechatplugin.use:
    description: Izinkan pemain menggunakan perintah voice chat
    default: true
