name: SimpleVoiceChatPlugin
version: 1.0
main: com.example.voicechatplugin.Main
api-version: 1.20
commands:
  voicechat:
      description: Mengelola grup voice chat
          usage: /voicechat [create|join|leave|list] [nama_grup]
              permission: voicechat.use
              permissions:
                voicechat.use:
                    description: Izin untuk menggunakan voice chat
                        default: true